server: 
  port: 9003
spring: 
  application:  
    name: huahua-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.117.83:3306/huahua_qa?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
  instance:
    prefer-ip-address: true